---
- name: RWX to tmp directory
  file:
    path: /tmp
    mode: 0777
    recurse: yes
  ignore_errors: yes
  become: true

- name: create directory to store the packages
  file:
    path: "{{download_location}}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0775
    recurse: yes
  become: true

- name: install pip, tar and ksh packages
  yum: name={{ item }} state=present
  with_items:
      - python-pip
      - zip
      - unzip
      - ksh
      - tar
  become: true

- name: install boto
  pip: name={{ item }} state=present
  with_items:
      - boto3
  become: true

- include: check_and_download.yaml
  with_items:
    - "{{packages_to_download}}"
