---
- name: install zip/unzip, tar and ksh packages
  yum: name={{ item }} state=present
  with_items:
      - zip
      - unzip
      - ksh
      - tar
  become: true
- name: Unarchive setup Tools zip file
  unarchive:
   src: /opt/binaries/{{ setuptools_file }}
   dest: /opt/binaries/
   copy: no
  ignore_errors: yes
- name: Install setup Tools
  command: /bin/bash -c "python setup.py install" chdir=/opt/binaries/{{ setuptools_dir }}
  become: true
  ignore_errors: yes

- name: install packages
  pip:
   name: file:/opt/binaries/{{ item }}
  become: true
  ignore_errors: yes
  with_items:
    - "{{install_binaries}}"