---
- name: "configure the {{package_name}} API"
  debug:
    msg: "configure the {{package_name}} API"
- name: "Ensures {{install_base_dir}}/{{deploy_context_root}} dir exists"
  file:
    path: "{{install_base_dir}}/{{deploy_context_root}}"
    follow: yes
    state: directory
  become: true

- name: Ensure gtar/unzip is installed on target machine
  package: name=unzip state=present
  become: true

- name: Unzip Tar file
  unarchive:
    src: "{{ playbook_dir }}/dist/{{ package_name }}"
    dest: "{{install_base_dir}}/{{deploy_context_root}}/"
    follow: yes
    mode: 0775
    owner: {{app_owner}}
    group: {{app_owner}}
  become: true

- name: Permissions for the artifacts
  file:
    path: "{{install_base_dir}}/{{deploy_context_root}}/"
    follow: yes
    mode: 0775
    owner: {{app_owner}}
    group: {{app_owner}}
    recurse: yes
  become: true
  
#    - name: restart service from init.d
#      service: name=pys3viewerapi state=restarted
#      become: true